### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by bluelotus03** [Climate-Refugee-Stories/crs-website#24]
- [x]  Logo background - needs to stay a circle
- [x]  Logo & Tagline need to move down to center 

Current layout:
![Screenshot 2022-01-25 9 30 05 PM](https://user-images.githubusercontent.com/25125692/151094099-5c2b9394-5f17-4cbf-bf32-97b91d44573c.png)

**Comment by elreydetoda** [comment]
Closed with this: https://github.com/Climate-Refugee-Stories/crs-website/pull/27
