### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by bluelotus03** [Climate-Refugee-Stories/crs-website#43]
Add ability to create/edit:
- [x] Home Page Info
- [x] About Info
  - [x]  Intro Info
  - [x]  Team Members
  - [x]  In the Media Info
- [x] Archive entries
- [x] Stories entries
  - [x] Place to add tags for searching 
- [x] Resources (diff types)
- [x] Change [this](https://github.com/Climate-Refugee-Stories/crs-website/blob/feat/Content-Management-System/static/admin/config.yml#L4) back to master
- [x] render custom shortcodes

going to be looking [at this](https://github.com/GWC-UNCC/axe-hacks-2022/tree/58d796e7ddea3d7b7b420b584af9f090c71c460c/content) for a lot of inspiration on how to make it editable from MD files.

useful links:
- https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent
- https://www.netlifycms.org/docs/widgets/
- https://www.netlifycms.org/docs/collection-types/
- https://github.com/sharadcodes/hugo-shortcodes-netlify-cms/blob/master/src/gist.js
- https://github.com/netlify/netlify-cms/issues/2727
- https://github.com/netlify-templates/one-click-hugo-cms/blob/main/site/static/admin/

**Comment by elreydetoda** [comment]
found out you can [modify toml files](https://github.com/Climate-Refugee-Stories/crs-website/pull/73) with [netlify CMS](https://www.netlifycms.org/docs/configuration-options/#extension-and-format)...so probably should configure that...
